import React, { useEffect, useState } from "react";
import api from "../apiInterceptor";
import { toast } from "react-toastify";

const VendorQrRequests = () => {
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(false);

  const fetchRequests = async () => {
    try {
      setLoading(true);
      const { data } = await api.get("/api/v1/vendor/qr-requests");
      setRequests(data.requests || []);
    } catch (error) {
      console.error(error);
      toast.error("Failed to load QR requests.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRequests();
  }, []);

  const handleAction = async (id, action) => {
    try {
      setLoading(true);
      await api.post(`/api/v1/vendor/qr-requests/${id}/${action}`);
      toast.success(
        action === "approve"
          ? "Request approved successfully."
          : "Request rejected successfully.",
      );
      fetchRequests();
    } catch (error) {
      console.error(error);
      toast.error(error.response?.data?.error || "Failed to update request.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4">
      <div className="max-w-6xl mx-auto">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">
              Vendor QR Requests
            </h1>
            <p className="mt-2 text-gray-600">
              Review customer point requests generated by your QR codes.
            </p>
          </div>
        </div>

        <div className="rounded-xl bg-white p-6 shadow-sm">
          {requests.length === 0 ? (
            <div className="text-center text-gray-600">
              No QR requests available yet.
            </div>
          ) : (
            <div className="space-y-4">
              {requests.map((request) => (
                <div
                  key={request.request_id}
                  className="rounded-2xl border border-slate-200 p-5"
                >
                  <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                    <div className="flex gap-4 items-start flex-1">
                      {/* Profile Picture */}
                      <div className="flex-shrink-0">
                        {request.customer?.userProfile?.avatar ? (
                          <img
                            src={request.customer.userProfile.avatar}
                            alt={request.customer?.name || "Customer"}
                            className="w-16 h-16 rounded-full object-cover border-2 border-blue-300"
                          />
                        ) : (
                          <div className="w-16 h-16 rounded-full bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center text-white font-bold text-xl border-2 border-blue-300">
                            {request.customer?.name
                              ? request.customer.name.charAt(0).toUpperCase()
                              : "?"}
                          </div>
                        )}
                      </div>
                      {/* Customer Info */}
                      <div className="space-y-2 flex-1">
                        <p className="text-sm text-gray-500">Customer</p>
                        <p className="text-lg font-semibold text-gray-900">
                          {request.customer?.name || "Unknown"}
                          {request.customer?.mobile
                            ? ` (${request.customer.mobile})`
                            : ""}
                        </p>
                        <p className="text-sm text-gray-600">
                          Points requested:{" "}
                          <span className="font-semibold">
                            {request.points}
                          </span>
                        </p>
                        <p className="text-sm text-gray-600">
                          QR title:{" "}
                          <span className="font-medium">
                            {request.qrCode?.title || "N/A"}
                          </span>
                        </p>
                        <p className="text-sm text-gray-600">
                          Created:{" "}
                          {new Date(request.created_at).toLocaleString()}
                        </p>
                        <p className="text-sm text-gray-600">
                          Status:{" "}
                          <span className="font-semibold">
                            {request.status}
                          </span>
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {request.status === "PENDING" ? (
                        <>
                          <button
                            onClick={() =>
                              handleAction(request.request_id, "approve")
                            }
                            disabled={loading}
                            className="rounded-full bg-green-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-green-700 disabled:opacity-60"
                          >
                            Approve
                          </button>
                          <button
                            onClick={() =>
                              handleAction(request.request_id, "reject")
                            }
                            disabled={loading}
                            className="rounded-full bg-red-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-red-700 disabled:opacity-60"
                          >
                            Reject
                          </button>
                        </>
                      ) : (
                        <span className="inline-flex items-center rounded-full bg-slate-100 px-3 py-1 text-sm font-medium text-slate-700">
                          {request.status}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default VendorQrRequests;
